--
-- DDL for "Alza Banner Campaign Monitoring"
--

CREATE TABLE dbo.Campaign (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  Name NVARCHAR(255) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NULL
);

CREATE TABLE dbo.Site (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  Domain NVARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE dbo.BannerPosition (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  SiteID UNIQUEIDENTIFIER NOT NULL,
  Width INT NOT NULL,
  Height INT NOT NULL,
  PricingType CHAR(3) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  CONSTRAINT FK_BannerPosition_Site FOREIGN KEY (SiteID) REFERENCES dbo.Site(ID)
);

CREATE TABLE dbo.Banner (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  PositionID UNIQUEIDENTIFIER NOT NULL,
  CampaignID UNIQUEIDENTIFIER NOT NULL,
  Width INT NOT NULL,
  Height INT NOT NULL,
  CONSTRAINT FK_Banner_BannerPosition FOREIGN KEY (PositionID) REFERENCES dbo.BannerPosition(ID),
  CONSTRAINT FK_Banner_Campaign FOREIGN KEY (CampaignID) REFERENCES dbo.Campaign(ID)
);

CREATE TABLE dbo.Click (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  BannerID UNIQUEIDENTIFIER NOT NULL,
  ClickDate DATETIME2 NOT NULL,
  CONSTRAINT FK_Click_Banner FOREIGN KEY (BannerID) REFERENCES dbo.Banner(ID)
);

CREATE TABLE dbo.[Order] (
  ID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
  CustomerID UNIQUEIDENTIFIER NOT NULL,
  OrderDate DATETIME2 NOT NULL,
  Revenue DECIMAL(12,2) NOT NULL
);

CREATE TABLE dbo.OrderBanner (
  OrderID UNIQUEIDENTIFIER NOT NULL,
  BannerID UNIQUEIDENTIFIER NOT NULL,
  PRIMARY KEY (OrderID, BannerID),
  CONSTRAINT FK_OrderBanner_Order FOREIGN KEY (OrderID) REFERENCES dbo.[Order](ID),
  CONSTRAINT FK_OrderBanner_Banner FOREIGN KEY (BannerID) REFERENCES dbo.Banner(ID)
);
